name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
    - name: "Fuck you github"
      run: >
        echo "Github sucks"