name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci-job:
    runs-on: ubuntu-latest
    container:
      image: juanzolotoochin/monorepo-ci:latest

    steps:
    # - uses: actions/checkout@v2
    - name: Checkout
      working-directory: /workdir/monorepo
      run: git checkout $GITHUB_SHA
    - name: Build and Test
      working-directory: /workdir/monorepo
      run: USER=bazelisk test //... --build_metadata=ROLE=CI --bes_backend=grpcs://cloud.buildbuddy.io --bes_results_url=https://app.buildbuddy.io/invocation/ --build_metadata=USER=ci_github_${{ github.event_name }}
