name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci-job:
    runs-on: ubuntu-latest
    container:
      image: juanzolotoochin/monorepo-ci:latest

    steps:
    - name: Debug Info
      run: |
        echo "USER=$USER"
        echo "HOME=$HOME"
    - name: Checkout
      run: |
        git config user.name mrGitHub
        git config user.email soemthing@mail.com
        git config github.token ${{ secrets.GITHUB_TOKEN }}
        git pull origin ${{ github.head_ref}}
      working-directory: /workdir/monorepo
    - name: Build and Test
      working-directory: /workdir/monorepo
      run: >
        bazelisk
        --output_user_root=/workdir/bazel-output-user-root
        --output_base=/workdir/bazel-output-base
        --install_base=/workdir/bazel-install-base
        test //...
        --build_metadata=ROLE=CI
        --bes_backend=grpcs://cloud.buildbuddy.io
        --bes_results_url=https://app.buildbuddy.io/invocation/
        --build_metadata=USER=ci_github_${{ github.event_name }}
        --disk_cache=/workdir/bazel-cache
        --repository_cache=/workdir/bazel-repository-cache

